name: Deploy - dev

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    needs: []
    uses: ./.github/workflows/_deploy-reusable.yml
    with:
      environment: dev
    secrets: inherit
